### ISSUE TITLE
Error in ./nuxt/client.js "Module build failed"

### ISSUE THREAD

**Issue by poldis** [creativetimofficial/nuxt-black-dashboard#11]
After downloading this repo and using npm install/yarn install, everytime I try to start it i get the error "Module build failed":
`Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                        friendly-errors 12:55:50  
Error: [BABEL] C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\.nuxt\client.js: --- PLACEHOLDER PACKAGE ---
This @babel/plugin-proposal-private-property-in-object version is not meant to
be imported. Something is importing
@babel/plugin-proposal-private-property-in-object without declaring it in its
dependencies (or devDependencies) in the package.json file.
Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies
to work around this error. This will make this message go away.
 (While processing: "C:\\Users\\poldi\\Documents\\programming\\discord\\dcr\\web\\nuxt-black-dashboard-master\\node_modules\\@nuxt\\babel-preset-app\\src\\index.js") 
    at Object.<anonymous> (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\plugin-proposal-private-property-in-object\lib\index.js:28:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@nuxt\babel-preset-app\src\index.js:166:6)       
    at async (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\gensync-utils\async.js:36:33)
    at async (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:186:15)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\full.js:181:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\gensync-utils\async.js:21:3)
    at Generator.next (<anonymous>)
    at step (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:269:25)
    at evaluateAsync (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:291:5)
    at Function.errback (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:113:7)
    at errback (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\gensync-utils\async.js:66:18)
    at async (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:188:17)
    at onFirstPause (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at loadPresetDescriptor (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\full.js:293:43)     
    at loadPresetDescriptor.next (<anonymous>)
    at recursePresetDescriptors (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\full.js:77:31)  
    at recursePresetDescriptors.next (<anonymous>)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\full.js:157:21
    at Generator.next (<anonymous>)
    at loadFullConfig (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\config\full.js:113:5)
    at loadFullConfig.next (<anonymous>)
    at transform (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\transform.js:20:44)
    at transform.next (<anonymous>)
    at step (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:269:25)
    at evaluateAsync (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:291:5)
    at errback (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\gensync\index.js:113:7)
    at stopHiding - secret - don't use this - v1 (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\errors\rewrite-stack-trace.js:47:12)
    at transform (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\@babel\core\lib\transform.js:39:72)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at transform (node:internal/util:346:12)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\babel-loader\lib\transform.js:15:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\babel-loader\lib\transform.js:3:103)
    at _next (C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\babel-loader\lib\transform.js:4:194)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\babel-loader\lib\transform.js:4:364
    at new Promise (<anonymous>)
    at C:\Users\poldi\Documents\programming\discord\dcr\web\nuxt-black-dashboard-master\node_modules\babel-loader\lib\transform.js:4:97
                                                                                                                                            friendly-errors 12:55:50  
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js`

**Comment by orderic-barnor** [comment]
Hi.
I have same problem. Nobody to find some fix?

**Comment by KimEJ** [comment]
try it
```
npm install --save-dev @babel/plugin-transform-private-property-in-object
```
